# Generated by Django 4.0.5 on 2022-06-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRPORT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(max_length=64)),
                ('czas', models.TimeField(max_length=64)),
                ('kurs', models.CharField(max_length=64)),
                ('rejs', models.CharField(max_length=64)),
                ('linia', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
            ],
        ),
    ]
