# Generated by Django 4.0.5 on 2022-06-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='rejs',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='status',
        ),
    ]
