# Generated by Django 4.0.5 on 2022-06-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_airport_rejs_remove_airport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='okres',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
