# Generated by Django 4.0.5 on 2022-06-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_airport_okres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='czas',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='data',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='kurs',
        ),
        migrations.AddField(
            model_name='airport',
            name='dni_tygodnia',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='godzina_o',
            field=models.TimeField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='godzina_p',
            field=models.TimeField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='miasto',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
